[package]
name = "silencia-mls"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
silencia-crypto = { path = "../silencia-crypto" }
thiserror = { workspace = true }
zeroize = { workspace = true }
